### ISSUE TITLE
为TMBot添加命令功能

### ISSUE THREAD

**Issue by Singl-Daemon** [TMBotDev/TMBot#24]
## 为TMBot添加命令功能

为TMBot添加命令功能，使其更加实用

> 绝对不是脑子一热就想起来的，一定不是(

![Screenshot_2023-04-15-18-54-27-34_9d26c6446fd7bb8e41d99b6262b17def](https://user-images.githubusercontent.com/97425519/232209710-7437ec23-de07-49fa-9f80-1409ca736694.jpg)

##  待办事项

- [x] 添加最基础的命令功能
- [x] 添加version等常用命令
- [x] 搓出来并完善注册命令API

> 希望提米不会丢进垃圾桶里(

**Comment by Singl-Daemon** [comment]
a3e14cae84f0337633e17761b19a9694c14f532b

**Comment by timiya233** [comment]
完善
